config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get 'welcome' => 'welcome#index'
  get 'welcome/index'
  
  get 'welcome/returning'
  
  resources :person
  
  get 'game/:id/results' => 'game#results', as: :results
  post 'game/:id/results' => 'game#update', as: :update

end

app/models/person.rb
class Person < ActiveRecord::Base
    validates :name, presence: false
    validates :height, :numericality => { :greater_than => 3, :less_than_or_equal_to => 8}, presence: true
    validates :weight, :numericality => { :greater_than => 70, :less_than_or_equal_to => 300}, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  end
  
  def results
    @id = params[:id]
    @person = Person.find_by(id:params[:id])
    
    dog_persons = 0
    cat_persons = 0
    
    if (@person != nil)
      if (@person.pet != nil)
          @pet = @person.pet
          if (@pet == 'Dog')
              @petimage = 'https://www.what-dog.net/Images/faces2/scroll0015.jpg'
          else
              @petimage = 'https://s-media-cache-ak0.pinimg.com/736x/07/c3/45/07c345d0eca11d0bc97c894751ba1b46.jpg'
          end
      else
          bmi = @person.weight * 0.45 / ((@person.height * 12 * 0.025) * (@person.height * 12 * 0.025))
          
          Person.find_each do |person|
            personbmi =  person.weight * 0.45 / ((person.height * 12 * 0.025) * (person.height * 12 * 0.025))
            
            if (bmi == personbmi)
              if (person.pet == 'Cat')
                cat_persons = cat_persons + 1
              else
                dog_persons = dog_persons + 1
              end
            end
          end
      
          puts dog_persons
          puts cat_persons
          
          if (dog_persons > cat_persons)
            @petimage = 'https://www.what-dog.net/Images/faces2/scroll0015.jpg'
            @pet = 'Dog'
            @notpet = 'Cat'
          else
            @petimage = 'https://s-media-cache-ak0.pinimg.com/736x/07/c3/45/07c345d0eca11d0bc97c894751ba1b46.jpg'
            @pet = 'Cat'
            @notpet = 'Dog'
          end
      end
    end
  end
  
  def update
      id = params[:id]
      pet = params[:person][:pet]
      person = Person.find_by(id: id)
      if (person != nil)
        person.update(pet: pet)
      end
      redirect_to controller: 'welcome', action: 'returning'
  end
end

app/controllers/person_controller.rb
class PersonController < ApplicationController

  def create
    @person = Person.find_by(name: params[:person][:name], height: params[:person][:height], weight: params[:person][:weight])
    
    id = 1
    if (@person != nil)
      if (@person.id != nil)
        id = @person.id
      end
    else
      @person = Person.new(person_params)
      @person.save
      if (@person.id != nil)
        id = @person.id
      end
    end
    
    redirect_to controller: 'game', action: 'results', id: id
  end
  
  private 
    def person_params
      params.require(:person).permit(:name, :height, :weight)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def load
    require 'csv'
    csv_text = File.read('/home/ubuntu/workspace/app/models/MOCK_DATA.csv')
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
      Person.create!(row.to_hash)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/game/results.html.erb
<div class="container">
    <div class="jumbotron">
        <h2>Result shows that your preferred pet is....</h2>
        <br />
        <br />
        <br />
        <p align="center"><img height="400" weight="400" src='<%= @petimage %>'</img>
        <br />
        <br />
        <br />
        <div class="row">
            <div class="col-sm-1 col-md-1 col-lg-1">
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
                <%= form_for :person, url: update_path do |f| %>
                    <div><%= f.hidden_field :id, :value => @id %></div>
                    <div><%= f.hidden_field :pet, :value => @pet %></div>
                    <button class="btn btn-success btn-lg" value="1" type="submit" role="button">
                          <i class="fa fa-check" aria-hidden="true"></i> &nbsp; Correct?
                    </button>
                <% end %>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4">
            </div>
            <div class="col-sm-3 col-md-3 col-lg-3">
                <%= form_for :person do |f| %>
                    <div><%= f.hidden_field :id, :value => @id %></div>
                    <div><%= f.hidden_field :pet, :value => @notpet %></div>
                    <button class="btn btn-danger btn-lg" value="0" type="submit" role="button">
                          <i class="fa fa-times" aria-hidden="true"></i> &nbsp; Or Wrong?
                    </button>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetGuesser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
    <div class="jumbotron">
        <h1>Hello there...</h1>
        <br />
        <br />
        <br />
        <p align="center">Got some few minutes to play the pet guessing game? It's gonna be fun.</p>
        <p align="center">Simply click the button below to start</p>
        <br />
        <br />
        <br />
        <div class="row">
            <div class="col-sm-5 col-md-5 col-lg-5">
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <span>
                  <button class="btn btn-success btn-lg"  data-toggle="modal" data-target="#myFormModal" role="button">
                      <i class="fa fa-hourglass-start" aria-hidden="true"></i> &nbsp; Start Game</button>
                  </span>
            </div>
        </div>
    </div>
    <div>
        <div class="modal fade" id="myFormModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                               <span aria-hidden="true">&times;</span>
                               <span class="sr-only">Close</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">
                            Just a few details needed
                        </h4>
                    </div>
                    <%= form_for :person, url: person_index_path do |f| %>
                        <div class="modal-body">
                          <div class="form-group">
                            <p>
                                <%= f.label :name %><br>
                                <%= text_field(:person, :name, required: false, class: "form-control") %>
                                <small id="usernameInfo" class="form-text text-muted">A name, a nickname maybe or your pet's name :)</small>
                            </p>
                          </div>
                          <br />
                          <div class="form-group">
                            <p>
                                <%= f.label :height %><br>
                                <%= number_field(:person, :height, in: 3.0..8.0, step: 0.1, required: true, class: "form-control") %>
                                <small id="heightInfo" class="form-text text-muted">We need your height (in ft)</small>
                            </p>
                          </div>
                          <br />
                          <div class="form-group">
                            <p>
                                <%= f.label :weight %><br>
                                <%= number_field(:person, :weight, in: 70.0..300.0, step: 0.1, required: true, class: "form-control") %>
                                <small id="weightInfo" class="form-text text-muted">Errr... and your weight (lb) too?</small>
                            </p>
                          </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal"> Close </button>
                            <button type="submit" class="btn btn-primary"> Find Your Pet </button>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
      </div>
</div>

app/views/welcome/returning.html.erb
<div class="container">
    <div class="jumbotron">
        <h2>Hope that was fun...</h1>
        <br />
        <br />
        <br />
        <p align="center">You can play again by clicking the button below to start</p>
        <br />
        <br />
        <br />
        <div class="row">
            <div class="col-sm-5 col-md-5 col-lg-5">
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <span>
                  <button class="btn btn-success btn-lg"  data-toggle="modal" data-target="#myFormModal" role="button">
                      <i class="fa fa-hourglass-start" aria-hidden="true"></i> &nbsp; Start Game</button>
                  </span>
            </div>
        </div>
    </div>
    <div>
        <div class="modal fade" id="myFormModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                               <span aria-hidden="true">&times;</span>
                               <span class="sr-only">Close</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">
                            Just a few details needed
                        </h4>
                    </div>
                    <%= form_for :person, url: person_index_path do |f| %>
                        <div class="modal-body">
                          <div class="form-group">
                            <p>
                                <%= f.label :name %><br>
                                <%= text_field(:person, :name, required: false, class: "form-control") %>
                                <small id="usernameInfo" class="form-text text-muted">A name, a nickname maybe or your pet's name :)</small>
                            </p>
                          </div>
                          <br />
                          <div class="form-group">
                            <p>
                                <%= f.label :height %><br>
                                <%= number_field(:person, :height, in: 3.0..8.0, step: 0.1, required: true, class: "form-control") %>
                                <small id="heightInfo" class="form-text text-muted">We need your height (in ft)</small>
                            </p>
                          </div>
                          <br />
                          <div class="form-group">
                            <p>
                                <%= f.label :weight %><br>
                                <%= number_field(:person, :weight, in: 70.0..300.0, step: 0.1, required: true, class: "form-control") %>
                                <small id="weightInfo" class="form-text text-muted">Errr... and your weight (lb) too?</small>
                            </p>
                          </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal"> Close </button>
                            <button type="submit" class="btn btn-primary"> Find Your Pet </button>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
      </div>
</div>